'use strict';

var $TypeError = require('es-errors/type');

var Call = require('./Call');
var CompletionRecord = require('./CompletionRecord');
var GetMethod = require('./GetMethod');
var IsCallable = require('./IsCallable');
<<<<<<< HEAD

var isObject = require('../helpers/isObject');
=======
var Type = require('./Type');
>>>>>>> 680064e5fdc85884a37bd24dfb3394d654d8dfba

// https://262.ecma-international.org/6.0/#sec-iteratorclose

module.exports = function IteratorClose(iterator, completion) {
<<<<<<< HEAD
	if (!isObject(iterator)) {
=======
	if (Type(iterator) !== 'Object') {
>>>>>>> 680064e5fdc85884a37bd24dfb3394d654d8dfba
		throw new $TypeError('Assertion failed: Type(iterator) is not Object');
	}
	if (!IsCallable(completion) && !(completion instanceof CompletionRecord)) {
		throw new $TypeError('Assertion failed: completion is not a thunk representing a Completion Record, nor a Completion Record instance');
	}
	var completionThunk = completion instanceof CompletionRecord ? function () { return completion['?'](); } : completion;

	var iteratorReturn = GetMethod(iterator, 'return');

	if (typeof iteratorReturn === 'undefined') {
		return completionThunk();
	}

	var completionRecord;
	try {
		var innerResult = Call(iteratorReturn, iterator, []);
	} catch (e) {
		// if we hit here, then "e" is the innerResult completion that needs re-throwing

		// if the completion is of type "throw", this will throw.
		completionThunk();
		completionThunk = null; // ensure it's not called twice.

		// if not, then return the innerResult completion
		throw e;
	}
	completionRecord = completionThunk(); // if innerResult worked, then throw if the completion does
	completionThunk = null; // ensure it's not called twice.

<<<<<<< HEAD
	if (!isObject(innerResult)) {
=======
	if (Type(innerResult) !== 'Object') {
>>>>>>> 680064e5fdc85884a37bd24dfb3394d654d8dfba
		throw new $TypeError('iterator .return must return an object');
	}

	return completionRecord;
};
